- name: httpd 포트 변경
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    vars.yml
  tasks:
    - name: httpd 포트 변경
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: '^Listen\s'
        line: "Listen {{ webport }}"
      notify:
        - httpd_restart

  handlers:
    - name: httpd_restart
      service:
        name: httpd
        state: restarted
